# Adapted from GitHub Actions MWE for Docker containers
# https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action
# Started as main.yml in root folder

name: AutoGrader-PS2   # Shows in the 'Workflows' section (left sidebar) of the GitHub Actions tab

on:                             # What is going to trigger this Workflow?
  push:
    branches: [ ps2 ]

jobs:                           # What actually needs done? 1+ jobs can be added, will run in parallel by default
  ag-ps2:                       # Name for your consumption only: is not obviously exposed anywhere
    name: 'Autograding PS2'   # Shows in the 'Jobs' section (left sidebar) of the Actions>Runs view
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: '`Checkout` hook (standard) - REQd for local actions'    # Shows as a foldable/expandable entry in the Runs log interface
        uses: actions/checkout@v2
      - name: 'Custom Step [1]: Firing up the AutoGrader action.yml'
        uses: ./.github/actions/AG
        id: mona
        # with:
          # who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: 'Custom Step [2]: What time did we run this?'
        run: echo "The time was ${{ steps.mona.outputs.time }}"
