# Adapted from GitHub Actions MWE for Docker containers
# https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action
# Started as main.yml in root folder

name: AutoGrader-PS2   # Shows in the 'Workflows' section (left sidebar) of the GitHub Actions tab

on:                             # What is going to trigger this Workflow?
  push:
    branches: [ ps2 ]

jobs:                           # What actually needs done? 1+ jobs can be added, will run in parallel by default
  ag-ps2:                       # Name for your consumption only: is not obviously exposed anywhere
    name: 'Autograding PS2'   # Shows in the 'Jobs' section (left sidebar) of the Actions>Runs view
    runs-on: ubuntu-latest
    container: dalexhughes/w241
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: '`Checkout` hook (standard) - REQd for EACH local action'    # Shows as a foldable/expandable entry in the Runs log interface
        uses: actions/checkout@v2

      - id: copy-answers-to-home
        name: 'Custom Step [1]: Move answers to persistent HOME'
        shell: bash
        run: |
          sudo apt-get install tree
          cp -r "${GITHUB_WORKSPACE}/${GITHUB_ACTOR}" "${HOME}/${GITHUB_ACTOR}"
        # echo "GitHub Action filesystem"
        # echo "GH Workspace for local repo:"
        # tree -L 2 "${GITHUB_WORKSPACE}"

      - id: fetch-test-suite-from-irepo
        name: 'Custom Step [2]: Go grab testing suite from instructor repo'
        uses: actions/checkout@v2
        with:
          repository: TSSlade/autograder_secrets   # The (private) repo where our data is living
          ref: ps2                                  # The specific branch to be checked out
          token: ${{ secrets.w241_autograder }}     # This PAT needs to be configured in the src repo (i.e. the one mentioned 2 lines up)

      - id: copy-suite-to-home
        name: "Custom Step [3]: Setting up the testing suite"
        shell: bash
        run: |
          mkdir "${GITHUB_WORKSPACE}/student"
          cp -r "${HOME}/${GITHUB_ACTOR}" "${GITHUB_WORKSPACE}/student/${GITHUB_ACTOR}"
        # echo "GH HOME:"
        # tree -L 3 "${HOME}"
        # echo "Currently here:" `pwd`
        # tree -L 2 "${GITHUB_WORKSPACE}"

      - id: execute-testing-suite
        name: 'Custom Step [7]: Running test suite'
        shell: bash
        # run: echo "${GITHUB_ACTION_PATH}"
        run: |
          cd "./ps2"
          echo "Currently in:" `pwd`
          cp -r "../student/${GITHUB_ACTOR}/questions/" "./answers/"
          chmod +x ./alex.R
          echo "Launch test suite"
          Rscript -e "library(knitr); library(testthat); loadedNamespaces(); source('./alex.R');"
          echo "Finished with ${GITHUB_ACTOR}"
        # echo "Contents of -student- folder:"
        # ls -lah ./student/${GITHUB_ACTOR}
        # tree -L 2 .
        # ls -lah .

# delete-artifacts:
#   runs-on: ubuntu-latest
#   steps:
#     - uses: kolpav/purge-artifacts-action@v1
#       with:
#         token: ${{ secrets.GITHUB_TOKEN }}
#         # expire-in: 7days # Set this to 0 to delete all artifacts
#         expire-in: 0 # Set this to 0 to delete all artifacts


# cleanup_job:
#     needs: [your_last_job]
#     if: always()
#     runs-on: ubuntu-latest
#     steps:
#     - name: call webhook to delete artifacts
#       env:
#         FOR_WEBHOOKS_SECRET: ${{ secrets.FOR_WEBHOOKS_SECRET }}
#       run: |
#         echo "::add-mask::$FOR_WEBHOOKS_SECRET"
#         curl --verbose --fail --show-error --location --request POST "https://api.github.com/repos/$GITHUB_REPOSITORY/dispatches" --header "Authorization: token $FOR_WEBHOOKS_SECRET" --header 'Content-Type: application/json' --header 'Accept: application/vnd.github.everest-preview+json' --data-raw "{ \"event_type\": \"delete_all_artifacts\", \"client_payload\": {\"parent_runid\": \"$GITHUB_RUN_ID\", \"parent_repo\": \"$GITHUB_REPOSITORY\"} }"