# Adapted from GitHub Actions MWE for Docker containers
# https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action
# Started as main.yml in root folder

name: AutoGrader-PS2   # Shows in the 'Workflows' section (left sidebar) of the GitHub Actions tab

on:                             # What is going to trigger this Workflow?
  push:
    branches: [ ps2 ]

jobs:                           # What actually needs done? 1+ jobs can be added, will run in parallel by default
  ag-ps2:                       # Name for your consumption only: is not obviously exposed anywhere
    name: 'Autograding PS2'   # Shows in the 'Jobs' section (left sidebar) of the Actions>Runs view
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: '`Checkout` hook (standard) - REQd for EACH local action'    # Shows as a foldable/expandable entry in the Runs log interface
        uses: actions/checkout@v2

      - id: Fetch-Suite
        name: 'Custom Step [1]: Go grab testing suite from instructor repo'
        uses: actions/checkout@v2
        with:
          repository: TSSlade/autograder_secrets   # The (private) repo where our data is living
          ref: ps2                                  # The specific branch to be checked out
          token: ${{ secrets.w241_autograder }}     # This PAT needs to be configured in the src repo (i.e. the one mentioned 2 lines up)
        run: |
          echo "GitHub Action filesystem:"
          ls -lah "/github"
          echo "GH Workspace:"
          ls -lah "${GITHUB_WORKSPACE}"
          echo "GH Event Path:"
          ls -lah "${GITHUB_EVENT_PATH}"
          echo "GH root:"
          ls -lah "/"

      - name: '`Checkout` hook (standard) - REQd for EACH local action'    # Shows as a foldable/expandable entry in the Runs log interface
        uses: actions/checkout@v2

      - id: Docker-Up
        name: 'Custom Step [2]: Spinning up Docker Container via AG/action.yml'
        uses: ./.github/actions/AG                  # Runs DockerUp.sh at the end...

      - id: Copy-Suite
        name: 'Custom Step [3]: Copy the testing suite from the instructor repo to the ephemeral Docker container'
        shell: bash
        # run: echo "${GITHUB_ACTION_PATH}"
        run: |
          echo "Docker container filesystem:"
          ls -lah "/github"
          echo "GH Workspace:"
          ls -lah "${GITHUB_WORKSPACE}"
          echo "GH Event Path:"
          ls -lah "${GITHUB_EVENT_PATH}"
          echo "GH root:"
          ls -lah "/"
          echo "GH root/home:"
          ls -lah "/home"
          echo "GH root/mnt:"
          ls -lah "/mnt"
          # make file runnable, might not be necessary
          chmod +x "${GITHUB_WORKSPACE}/../.github/actions/AG/AG-move-ps2.sh"
          # run script
          "${GITHUB_WORKSPACE}/.github/actions/AG/AG-move-ps2.sh"

      # - id: Run-Suite
      #   name: 'Custom Step [4]: Run Alex's script over student folders'
      #   shell: bash
      #   run: |
      #     sh .github/actions/AG/AG-test-ps2.sh
      # Use the output from the `hello` step

      - name: 'Custom Step [5]: What time did we run this?'
        run: echo "The time was ${{ steps.Docker-Up.outputs.time }}"


    # steps:
    #   - name: Access contents of private repo
    #     # env:
    #       # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     uses: actions/checkout@v2
    #     with:
    #       repository: TSSlade/autograder_secrets
    #       token: ${{ secrets.w241_autograder }}