# Adapted from GitHub Actions MWE for Docker containers
# https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action
# Started as main.yml in root folder

on:
  push:
    branches: [ greetings ]

jobs:
  hello_mona_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: w241_autograder/who-to-greet@v1
      # uses: ./entrypoint.sh
      with:
        who-to-greet: 'Mona...the Octocat'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"

  hello_private_job:
    runs-on: ubuntu-latest
    name: A private job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./  # Uses an action in the root directory
        id: hello
        with:
          who-to-greet: 'Private Pyle'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"