# Adapted from GitHub Actions MWE for Docker containers
# https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action
# Started as main.yml in root folder

name: Minimum Working Example

on:
  push:
    branches: [ greetings ]

jobs:
  my-mwe:
    name: 'A minimum working example (MWE) :octocat:'
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: '`Checkout` hook (standard)'
        uses: actions/checkout@v2
      - name: 'Custom Step [1]: "Hello world!" (the MWE)'
        uses: ./.github/actions/MWE
        id: mona
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: 'Custom Step [2]: What time did we run this?'
        run: echo "The time was ${{ steps.mona.outputs.time }}"

# name: R

# on:
#   push:
#     branches: [ submission ]
#   pull_request:
#     branches: [ submission ]

# jobs:
#   build:
#     runs-on: macOS-latest
#     strategy:
#       matrix:
#         r-version: [3.5]

#     steps:
#       - run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV
#       - uses: actions/checkout@v2
#       - name: Set up R ${{ matrix.r-version }}
#         uses: r-lib/actions/setup-r@ffe45a39586f073cc2e9af79c4ba563b657dc6e3
#         with:
#           r-version: ${{ matrix.r-version }}
# #Consider moving the package installs to the docker creation
#       - name: Install gapminder
#         run: install.packages("gapminder")
#         shell: Rscript {0}
# #Consider copying the files from a separate github that the docker instance has access to
# #This step also needs to grab the student's code
#       - name: copy files
#         run: sudo cp R_checker.R /Users/Shared/R_checker.R
#         shell: bash
#       - name: Run a Script
#         run: Rscript /Users/Shared/R_checker.R